name: ISANTEPLUS QA
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest         
    steps:
      - name: Checkout docker isanteplus server
        uses: actions/checkout@v2
        with:
          repository: IsantePlus/docker-isanteplus-server
          ref: ci
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}    
      - name:  Spin UP isanteplus server 
        run:  |
              docker-compose -f docker-compose.ci.yaml up -d
      - name: Sleep for 4 minutes 
        run: sleep 4m
        shell: bash     
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout isanteplus qaframework
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
      - name: Run isanteplus QA and Publish Test results
        run: |
          echo "cucumber.publish.enabled=true" > src/test/resources/cucumber.properties
          mvn clean install -Dcucumber.filter.tags='@null' 
          mvn test   
          curl -X POST \
          https://studio.cucumber.io/cucumber_project/results \
          -F messages=@./target/cucumber.ndjson  \
          -H "project-access-token: ${{secrets.CUCUMBER_IO_TOKEN}}" \
          -H "provider: github" \
          -H "repo: ${{github.repository}}" \
          -H "branch: main" \
          -H "revision: ${{github.sha}}"
